# Generated by Django 5.2.5 on 2025-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("entry_date", models.DateField(auto_now_add=True)),
                ("expiration_date", models.DateField()),
            ],
        ),
    ]
