# Generated by Django 5.2.5 on 2025-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_item_per_user",
        ),
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
        migrations.AlterField(
            model_name="item",
            name="item_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
