# Generated by Django 5.2.5 on 2025-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_remove_item_unique_item_per_user_remove_item_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
