# Generated by Django 5.2.5 on 2025-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_number",
            field=models.CharField(max_length=100),
        ),
    ]
