# Generated by Django 5.2.5 on 2025-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_alter_item_item_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_steel",
            field=models.BooleanField(default=False),
        ),
    ]
